spring:
  application:
    name: inventory-service

  datasource:
    url: jdbc:postgresql://postgres:5432/inventory_db
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  batch:
    jdbc:
      schema: classpath:org/springframework/batch/core/schema-postgresql.sql
      initialize-schema: never
      # table-prefix: batch_schema.
      # Résultat final : les tables seront créées comme batch_schema.batch_job_instance, batch_schema.batch_job_execution, etc.

  jackson:
    time-zone: UTC

  kafka:
    bootstrap-servers: kafka:29092
    consumer:
      group-id: inventory-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.add.type.headers: false
      auto-offset-reset: earliest

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    enabled: true

server:
  port: 8083

logging:
  level:
    ma.emsi.inventoryservice: DEBUG
    ma.springframework.batch: DEBUG
    ma.springframework.scheduling: DEBUG