spring:
  application:
    name: notification-service

  datasource:
    url: jdbc:postgresql://postgres:5434/notification_db
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # Configuration Kafka
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: notification-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

  # Configuration Email (Gmail exemple)
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:testmailing1995@gmail.com}
    password: ${MAIL_PASSWORD:ukji fzzj jfxn dton}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

server:
  port: 8084

# Configuration Inventory
inventory:
  admin-email: ${ADMIN_EMAIL:admin@ebank.com}

# Configuration SMS Provider
sms:
  provider:
    enabled: false  # Activer quand un provider est configuré
    api-key: ${SMS_API_KEY:}
    # Twilio example
    account-sid: ${TWILIO_ACCOUNT_SID:}
    auth-token: ${TWILIO_AUTH_TOKEN:}
    from-number: ${TWILIO_FROM_NUMBER:}

# Logging
logging:
  level:
    com.ebank.notificationservice: DEBUG
    org.springframework.kafka: INFO
    org.apache.kafka: WARN
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"