spring:
  application:
    name: product-service

  datasource:
    url: jdbc:postgresql://localhost:5434/product_db
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  batch:
    jdbc:
      initialize-schema: never
    job:
      enabled: false

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

server:
  port: 8081

logging:
  level:
    ma.emsi.productservice: DEBUG