spring:
  application:
    name: supplier-service

  datasource:
    url: jdbc:postgresql://postgres:5432/supplier_db
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  batch:
    jdbc:
      initialize-schema: never
    job:
      enabled: false

server:
  port: 8082

logging:
  level:
    ma.emsi.supplierservice: DEBUG